networks:
  gridnet:
    driver: bridge

services:
  web:
    image: nginx
    container_name: grids_web
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
      - ../web:/web
    ports:
      - "8080:80"
    networks:
      - gridnet

  api:
    image: datagrid-api
    container_name: grids_api
    ports:
      - "8081:8080"
    networks:
      - gridnet